### ISSUE TITLE
.we 和 .vue 的语法差异

### ISSUE THREAD

**Issue by Hanks10100** [Hanks10100/weex#12]
## Overview

| 描述 | Weex | Vue |
| ---- | ---- | --- |
| 类名 | `class="btn btn-{{type}}"` | `:class="['btn', 'btn-' + type]"` |
| if 指令 | `if="{{!foo}}"`  | `v-if="!foo"` |
| 循环指令 | `repeat="{{item in list}}"`  | `v-for="item in list"` |
| 事件绑定 | `onclick="handler"` | `@click="handler"` |
| 样式绑定 | `style="color:{{textColor}}"` | `:style="{ color: textColor }"` |
| 属性绑定 | `src="{{rightItemSrc}}"` | `:src="rightItemSrc"` |
|自定义的原生事件 | `onclick="xxx"` | `@click.native="xxx"` |
| 内容槽 | `<content></content>` | `<slot></slot>` |
| 初始化数据 | `data: { value: 'x' }` | `props: { value: { default: 'x' } }` |
| 标签 id | `id="xxx"` | `ref="xxx"` |
| 获取节点 | `this.$el('xxx')` | `this.$refs.xxx` |
| 触发自定义事件 | `this.$dispatch()` | `this.$emit()` |

**Comment by songsiqi** [comment]
可参考 `weex-vue-migration` 源码中的注释完善文档：

* [template-rewriter](https://github.com/songsiqi/weex-vue-migration/blob/master/src/template-rewriter/rewriter.js)
* [script-rewriter](https://github.com/songsiqi/weex-vue-migration/blob/master/src/script-rewriter/rewriter.js)

**Comment by Hanks10100** [comment]
moved to https://weex-project.io/cn/references/migration/difference.html
