### ISSUE TITLE
请将weex-vue-render和weex模块分开发布！

### ISSUE THREAD

**Issue by nicefan** [Hanks10100/weex#25]
现在npm 中的weex-vue-render中，直接包含了一个全局weex,无法在webpack中模块化工作！！！

**Comment by Hanks10100** [comment]
能够描述下详细问题？ 不太明白 【无法在webpack中模块化工作】是什么意思。

另外，这是我的个人仓库……

**Comment by nicefan** [comment]
抱歉，不甚打扰，在官方出的一些模板中，都是将weex-vue-render 和vue-runtime,放在html文件中，全局加载，但这样并不能在开发时，热更新。
我需要将weex像vue这样自动加载，
new webpack.ProvidePlugin({
Vue: 'vue'
})
这样我就方便web端开发及打包
当然，我的webpack配置是区分了web，和weex的。
现在我只能将weex-vue-render放外面，因为里面包含了weex全局模块。

2017年3月15日 18:30于 Hanks <notifications@github.com>写道：

能够描述下详细问题？ 不太明白 【无法在webpack中模块化工作】是什么意思。

另外，这是我的个人仓库……

―

**Comment by Hanks10100** [comment]
weex-vue-render 除了有 Weex 的组件，也有 Weex 的模块；如果不含 Weex 的模块程序没法正常运行的。（其实我还是不太理解 Weex 的模块哪里影响到了 Webpack 的配置）

Weex 现在仓库迁移到了 Apache 。建议你给 `dev@weex.incubator.apache.org` 发个邮件问这个问题（用英语），尽量提供完整的 webpack 配置，描述清楚你的需求。

> 另外给 `dev-subscribe@weex.incubator.apache.org` 发一封主题为 **request subscription** 的空邮件可以订阅我们的邮件列表，在那里能看到我们正在讨论的问题，也可以参与讨论。
